services:
  tomcat:
    container_name: tomcat
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_UN: ${SERVER_UN}
        SERVER_PW: ${SERVER_PW}
        TOMCAT_UN: ${TOMCAT_UN}
        TOMCAT_PW: ${TOMCAT_PW}
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:8080
      - ${SSH_PORT}:22
    #command: bash -c "cp /usr/local/tomcat/wars/*.war /usr/local/tomcat/webapps"
    volumes:
      - ${VOLS_WARS}:/usr/local/tomcat/wars/
      - ${VOLS_LOGS}:/usr/local/tomcat/logs/
      - ${VOLS_DATA}:/mnt/data
    extra_hosts:    
      - "srv-bx-val-d.lands.nsw:10.114.172.77"
      - "cls-sw-proxy.lands.nsw:10.114.16.66"
    networks:
      - localnet
networks:
  localnet:
    name: local-network
    external: true      
