version: '2'

services:
  tomcat:
    container_name: tomcat
    build:
      context: .
    ports:
      - ${HTTP_PORT}:8080
    volumes:
       - ${VOLS_WARS}:/usr/local/tomcat/wars/
       - ${VOLS_LOGS}:/usr/local/tomcat/logs/